Added functionality for Mark Messages as Read
Bindambc/whatsapp-business-java-api pull request #85
Opened 2023-04-17 15:07 UTC by pratsonii

Fixes #29

2023-04-19 00:43 UTC, Bindambc requested changes
Just some suggested changes. Thank you for the pull request.

2023-04-19 00:43 UTC, Bindambc commented on src/test/java/com/whatsapp/api/impl/WhatsappBusinessCloudApiTest.java
> +        Assertions.assertEquals(true, response.success());
`Assertions.assertEquals(true, response.success())` can be simplified to `assertTrue()`

2023-04-19 00:43 UTC, Bindambc commented on src/main/java/com/whatsapp/api/impl/WhatsappBusinessCloudApi.java
> +     * @param message       The {@link Message} object.
change javadoc text `{@link Message}` to `{@link ReadMessage}`, please

2023-04-21 07:55 UTC, Bindambc approved these changes

2023-04-21 07:55 UTC, merged

2023-05-19 15:17 UTC, ferasawadi commented
any ideas how to get the message id?

2023-05-23 03:14 UTC, Bindambc commented
> any ideas how to get the message id?

Hello @ferasawadi, the messages ID can be obtained through a webhook. You will need to set up a webhook in advance to receive the messages and be able to respond to them or mark them as read.

You can find more detailed instructions on how to configure the webhook at the following links: [link1](https://developers.facebook.com/docs/whatsapp/business-management-api/guides/set-up-webhooks) and [link2](https://developers.facebook.com/docs/whatsapp/cloud-api/webhooks/payload-examples).

This library provides support for deserializing the payloads received through the webhook. You can find an example of this here: [link3](https://github.com/Bindambc/whatsapp-business-java-api/blob/main/src/test/java/com/whatsapp/api/examples/WebHookExample.java).

I hope this can help you. Please, feel free to open an issue if you have any further questions.